# Generated by Django 5.2.8 on 2026-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='establishment',
            name='stripe_detail_submited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='establishment',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
