# Generated by Django 5.2.8 on 2026-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, choices=[('UNIT-1', 'Unit 1'), ('UNIT-2', 'Unit 2'), ('UNIT-3', 'Unit 3'), ('UNIT-4', 'Unit 4')], default='UNIT-1'),
        ),
    ]
