# Generated by Django 5.2.8 on 2026-01-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_appointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_document',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
