# Generated by Django 5.2.8 on 2026-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_establishment_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='stripe_detail_submited',
        ),
        migrations.AddField(
            model_name='establishment',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
