# Generated by Django 5.2.8 on 2026-01-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_alter_customer_id_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="paiment_method",
            new_name="payment_method",
        ),
    ]
