# Generated by Django 5.2.8 on 2026-01-26 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_remove_establishment_stripe_detail_submited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='stripe_onboarding_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
