# Generated by Django 5.2.8 on 2026-01-15 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
