# Generated by Django 5.2.8 on 2026-02-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_appointment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.establishment'),
        ),
    ]
